module.exports = {
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
    mainSidebar: ['intro', {
        'Guides': ['installation', 'wwui-custom-intro', 'ww-ui-style', 'ww-i18n', 'deploy']
    }, ]
};