# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  documentation:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: install
      run: npm ci
    - name: build
      run: npm run-script build
    # Runs a single command using the runners shell
    
    # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Build output to publish to the `gh-pages` branch:
        publish_dir: ./build
        # The following lines assign commit authorship to the official
        # GH-Actions bot for deploys to `gh-pages` branch:
        # https://github.com/actions/checkout/issues/13#issuecomment-724415212
        # The GH actions bot is used by default if you didn't specify the two fields.
        # You can swap them out with your own user credentials.
        user_name: github-actions[bot]
        user_email: actions@github.com
